Shop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Controlers;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;
        public ShopCartController(IAllCars carRep,ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;
        }
        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;
            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        
        }

       public RedirectToActionResult addToCart(int id)
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.id ==id);
            if (item != null)
            {
                _shopCart.AddToCart(item);

            }
            return RedirectToAction("Index");
        }
        
    }
}

Shop/Views/Shared/AllCars.cshtml
@model Car
<style>
    .gallery5 {
        overflow: hidden;
        width: 480px;
    }

        .gallery5 .ramka {
            float: left;
            margin-right: 10px;
            margin-bottom: 10px;
        }

        .gallery5 img {
            width: 200px;
            height: 200px;
            object-fit: cover;
        }
</style>
<div class="gallery5 ">
    <img class="ramka" src="@Model.img" alt="@Model.name" />
    <h2> @Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Price : @Model.price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Add to ShopCart</a></p>
</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark  bg-dark">
            <a class="navbar-brand" href="/">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item">
                        <a class="nav-link" href="/ShopCart">Shop cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List">All cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/electro">Electro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/classic">Fuel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/User/signUp">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/User/signIn">Sign In</a>
                    </li>

                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container mt-5" >
        @RenderBody()
    </div>
   
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>